"use client";
import { useState } from "react";

const D = [
"Algeria-dz-Ligue 1|Ligue 2|Cup",
"England-gb-eng-Premier League|Championship|FA Cup|League One",
"Spain-es-La Liga|La Liga 2|Copa del Rey",
"Germany-de-Bundesliga|2. Bundesliga",
"Italy-it-Serie A|Serie B",
"France-fr-Ligue 1|Ligue 2",
"Morocco-ma-Botola Pro|Botola 2",
"Egypt-eg-Premier League|Cup",
"Nigeria-ng-NPFL|Federation Cup",
"South Africa-za-PSL|Nedbank Cup",
"USA-us-MLS|US Open Cup",
"Brazil-br-Serie A|Serie B",
"Argentina-ar-Liga Profesional|Primera Nacional",
"Turkey-tr-Super Lig|1. Lig",
"Netherlands-nl-Eredivisie|Eerste Divisie",
"Portugal-pt-Primeira Liga|Segunda Liga",
"Belgium-be-Pro League|Challenger",
"Saudi Arabia-sa-Pro League|Division 1",
"Qatar-qa-Stars League|Second Division",
"Japan-jp-J1 League|J2 League",
"Mexico-mx-Liga MX|Expansion",
"Tunisia-tn-Ligue 1|Ligue 2",
"Senegal-sn-Ligue 1|Ligue 2",
"Ghana-gh-Premier League|Division One",
"Cameroon-cm-Elite One|Elite Two",
"Afghanistan-af-Premier|Cup",
"Albania-al-Superliga|Cup",
"Andorra-ad-Primera Divisio|Cup",
"Angola-ao-Girabola|Cup",
"Armenia-am-Premier League|Cup",
"Australia-au-A-League|Cup",
"Austria-at-Bundesliga|2. Liga",
"Azerbaijan-az-Premier League|Cup",
"Bahrain-bh-Premier League|Cup",
"Bangladesh-bd-Premier League|Cup",
"Belarus-by-Premier League|Cup",
"Benin-bj-Premier League|Cup",
"Bolivia-bo-Primera Division|Cup",
"Bosnia-ba-Premier League|Cup",
"Botswana-bw-Premier League|Cup",
"Bulgaria-bg-First League|Cup",
"Burkina Faso-bf-Premier League|Cup",
"Burundi-bi-Primus League|Cup",
"Cambodia-kh-Premier League|Cup",
"Canada-ca-Premier League|Cup",
"Chad-td-Premier League|Cup",
"Chile-cl-Primera Division|Cup",
"China-cn-Super League|League One",
"Colombia-co-Primera A|Primera B",
"Congo-cg-Ligue 1|Cup",
"Croatia-hr-HNL|First NL",
"Cyprus-cy-First Division|Second Division",
"Czech Republic-cz-First League|Second League",
"Denmark-dk-Superliga|1st Division",
"Ecuador-ec-Serie A|Serie B",
"Ethiopia-et-Premier League|Cup",
"Finland-fi-Veikkausliiga|Ykkonen",
"Gabon-ga-Championnat|Cup",
"Greece-gr-Super League|Super League 2",
"Guinea-gn-Ligue 1|Cup",
"Honduras-hn-Liga Nacional|Cup",
"Hungary-hu-NB I|NB II",
"Iceland-is-Besta Deild|1. Deild",
"India-in-ISL|I-League",
"Indonesia-id-Liga 1|Liga 2",
"Iran-ir-Pro League|Azadegan League",
"Iraq-iq-Stars League|Division 
